name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_PATH: "src/SklepCS-Manager.csproj"
  PROJECT_NAME: "SklepCS-Manager"
  OUTPUT_PATH: "./SklepCS-Manager"

jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c SklepCS-Manager -o ${{ env.OUTPUT_PATH }}

  Publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: Build
      run: dotnet publish ${{ env.PROJECT_PATH }} -c SklepCS-Manager -o ${{ env.OUTPUT_PATH }}
    - name: Zip
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: '${{ env.PROJECT_NAME }}-v${{ env.BUILD_NUMBER }}.zip'
        path: ${{ env.OUTPUT_PATH }}
    - name: SklepCS-Manager
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "${{ env.PROJECT_NAME }}-v${{ env.BUILD_NUMBER }}.zip"
        name: "v${{ env.BUILD_NUMBER }}"
        tag: "build-${{ env.BUILD_NUMBER }}"
        body: |
          ## Installation
          1. Download the [latest release](https://github.com/CS-GEJMERZY/SklepCS-Manager/releases/latest)
          2. Unzip the package and upload files to **_csgo/addons/counterstrikesharp/plugins_**
