name: Build

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches:
      - '*'
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_PATH: "src/SklepCS-Manager.csproj"
  PROJECT_NAME: "SklepCS-Manager"
  OUTPUT_PATH: "./SklepCS-Manager"

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ['build', 'publish']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build or Publish
      run: |
        if [ "${{ matrix.target }}" == "build" ]; then
          dotnet build ${{ env.PROJECT_PATH }} -c SklepCS-Manager -o ${{ env.OUTPUT_PATH }}
        elif [ "${{ matrix.target }}" == "publish" ]; then
          dotnet publish ${{ env.PROJECT_PATH }} -c SklepCS-Manager -o ${{ env.OUTPUT_PATH }}
        fi

  Publish:
    needs: Build
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c SklepCS-Manager -o ${{ env.OUTPUT_PATH }}

    - name: Zip
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: '${{ env.PROJECT_NAME }}-v${{ env.BUILD_NUMBER }}.zip'
        path: ${{ env.OUTPUT_PATH }}

    - name: Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "${{ env.PROJECT_NAME }}-v${{ env.BUILD_NUMBER }}.zip"
        name: "v${{ env.BUILD_NUMBER }}"
        tag: "build-${{ env.BUILD_NUMBER }}"
        body: |
          ## Installation
          1. Download the [latest release](https://github.com/CS-GEJMERZY/SklepCS-Manager/releases/latest)
          2. Unzip the package and upload files to **_csgo/addons/counterstrikesharp/plugins_**
